## NumPy
可以提供高效的数组运算

In [1]:
import numpy as np

In [8]:
my_arr = np.arange(100000)
my_list = list(range(100000))

%time for _ in range(10):my_arr2 = my_arr *2

CPU times: user 863 µs, sys: 969 µs, total: 1.83 ms
Wall time: 1.6 ms


In [7]:
%time for _ in range(10):my_list2 = [x*2 for x in my_list]

CPU times: user 53.3 ms, sys: 7.42 ms, total: 60.7 ms
Wall time: 59.7 ms


## ndarray 数组运算
把数组中每项都进行计算

In [9]:
## randn 生成服从标准正态分布的数组，数组维度由入参指定
data = np.random.randn(2,3)
data

array([[-0.07675345,  0.12092985, -0.21078834],
       [-0.73714721, -1.66710044,  0.28793469]])

In [10]:
data * 10

array([[ -0.76753454,   1.20929845,  -2.1078834 ],
       [ -7.3714721 , -16.67100435,   2.87934693]])

In [11]:
data + data

array([[-0.15350691,  0.24185969, -0.42157668],
       [-1.47429442, -3.33420087,  0.57586939]])

In [32]:
## *会传递到每一个对应位置相乘
data * data

array([[0.00589109, 0.01462403, 0.04443172],
       [0.54338601, 2.77922386, 0.08290639]])

In [33]:
## 比较会产生bool数组
arr = np.zeros((2,3))
data > arr

array([[False,  True, False],
       [False, False,  True]])

### shape属性，记录数组是几x几的

In [13]:
data.shape

(2, 3)

### dtype属性，记录数组数据类型

In [14]:
data.dtype

dtype('float64')

### ndim属性，记录是几维数组

In [17]:
data.ndim

2

## 数组生成
array(data,dtype),zeros(),ones(),empty()

In [15]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
data2 = [[1,2,3,4],[5,6,7,8]]
## array中可以指定dtype
arr2 = np.array(data2,dtype = np.float64)
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [23]:
##传入元组，生成指定shape的0数组
arr3 = np.zeros((2,3,2))
arr3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### arange()  range的数组版

In [26]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### astype()转换数据类型
可使用np.float64，其他数组类型arr1.dtype，或者类型代码’u4‘来指定类型

In [27]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [28]:
## astype会生成新的数组
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

## 索引和切片
### 一维数组索引和切片类似list

In [37]:
arr = np.arange(10)
arr[5]

5

In [36]:
## 切片是一个视图，赋值会改变原数组值
arr[3:5] = 12
arr

array([ 0,  1,  2, 12, 12,  5,  6,  7,  8,  9])

### 多维数组索引
可传入多个数轴上的索引

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.shape)
arr2d[2]

(3, 3)


array([7, 8, 9])

In [41]:
arr2d[2,2]

9

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d.shape)
arr3d[0,1]

(2, 2, 3)


array([4, 5, 6])

### 多维数组切片
可以进行多维度切片

In [45]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
##逗号隔开多组切片，示例选择第2行，0～1列
arr2d[1,:2]

array([4, 5])

### 布尔索引
使用数组比较产生bool数组，～可以取反，生成的是数据的copy

In [54]:
## 假设每个名字对应data中的一行，目前要把Bob对应的这行筛选出来
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.25899762,  1.20757134, -0.58479728,  1.57985703],
       [-1.49974506,  0.23311416, -0.2494428 ,  0.27358475],
       [ 1.64125312, -0.09549519, -0.83533012, -1.54010926],
       [ 2.1312733 ,  0.270353  , -1.03807708,  0.18271969],
       [ 0.98815636, -1.90217371, -1.85314337, -0.16526094],
       [-1.27213387, -1.10880046, -2.20270748,  0.32623747],
       [-0.27134638, -0.33530423,  1.55642791, -2.60976207]])

In [55]:
## 数组的比较产生bool数组
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [56]:
data[names == 'Bob',2:]

array([[-0.58479728,  1.57985703],
       [-1.03807708,  0.18271969]])

In [57]:
data[~(names == 'Bob')]

array([[-1.49974506,  0.23311416, -0.2494428 ,  0.27358475],
       [ 1.64125312, -0.09549519, -0.83533012, -1.54010926],
       [ 0.98815636, -1.90217371, -1.85314337, -0.16526094],
       [-1.27213387, -1.10880046, -2.20270748,  0.32623747],
       [-0.27134638, -0.33530423,  1.55642791, -2.60976207]])

In [58]:
## 可以使用&和|联合bool条件
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 0.25899762,  1.20757134, -0.58479728,  1.57985703],
       [ 1.64125312, -0.09549519, -0.83533012, -1.54010926],
       [ 2.1312733 ,  0.270353  , -1.03807708,  0.18271969],
       [ 0.98815636, -1.90217371, -1.85314337, -0.16526094]])

### 神奇索引
单个索引数组（注意使用方括号）

In [60]:
arr = np.random.randn(8,4)
arr

array([[ 1.00214212, -2.10447782,  0.01164115,  0.11191848],
       [-0.36280716, -1.39956393, -0.09469662,  0.96460483],
       [ 0.41665183, -0.52904802, -1.278777  ,  0.29053621],
       [ 0.56349037,  1.18653825,  1.60425923,  0.55899211],
       [-1.78267204,  2.95240475, -0.52588482, -1.26615581],
       [-1.69650228, -1.18741036, -0.5440334 , -1.18407203],
       [ 1.10808775, -2.345388  , -0.95007705,  1.43899969],
       [-0.14275992,  0.8912161 , -0.99783995,  0.64145758]])

In [62]:
## 挑选出指定行
arr[[4,3,0,6]]

array([[-1.78267204,  2.95240475, -0.52588482, -1.26615581],
       [ 0.56349037,  1.18653825,  1.60425923,  0.55899211],
       [ 1.00214212, -2.10447782,  0.01164115,  0.11191848],
       [ 1.10808775, -2.345388  , -0.95007705,  1.43899969]])

In [64]:
## 负索引从尾部选则
arr[[-2,-3,-5]]

array([[ 1.10808775, -2.345388  , -0.95007705,  1.43899969],
       [-1.69650228, -1.18741036, -0.5440334 , -1.18407203],
       [ 0.56349037,  1.18653825,  1.60425923,  0.55899211]])

传入多个索引数组时，不是选择矩形区域

In [65]:
arr[[1,5,7,2],[0,3,1,2]]

array([-0.36280716, -1.18407203,  0.8912161 , -1.278777  ])